version: '3.4'

services:
  bff:
    image: ${DOCKER_REGISTRY-}bff
    build:
      context: .
      dockerfile: BFF/Dockerfile
    depends_on:
      - products
      - baskets

  products:
    image: ${DOCKER_REGISTRY-}products
    build:
      context: .
      dockerfile: Products/Dockerfile

  baskets:
    image: ${DOCKER_REGISTRY-}baskets
    build:
      context: .
      dockerfile: Baskets/Dockerfile
