version: '3.4'

services:
  repr.web:
    image: ${DOCKER_REGISTRY-}reprweb
    build:
      context: ../C18/REPR
      dockerfile: ../../C19/REPR.Web/Dockerfile

  repr.bff:
    image: ${DOCKER_REGISTRY-}reprbff
    build:
      context: ../
      dockerfile: C19/REPR.BFF/Dockerfile
    depends_on:
      - repr.web
      